services:
  postgres:
    image: postgres:17-alpine
    container_name: odin-recruitment-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minichoper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=${N8N_LOCAL_DB_TYPE}
      - DB_POSTGRESDB_HOST=${N8N_LOCAL_DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${N8N_LOCAL_DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${N8N_LOCAL_DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${N8N_LOCAL_DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_LOCAL_DB_POSTGRESDB_PASSWORD}

      # neondb
      # - DB_POSTGRESDB_HOST=${N8N_NEON_DB_POSTGRESDB_HOST}
      # - DB_POSTGRESDB_PORT=${N8N_NEON_DB_POSTGRESDB_PORT:-5432}
      # - DB_POSTGRESDB_DATABASE=${N8N_NEON_DB_POSTGRESDB_DATABASE}
      # - DB_POSTGRESDB_USER=${N8N_NEON_DB_POSTGRESDB_USER}
      # - DB_POSTGRESDB_PASSWORD=${N8N_NEON_DB_POSTGRESDB_PASSWORD}
      # - DB_POSTGRESDB_SSL_ENABLED=${N8N_NEON_DB_POSTGRESDB_SSL_ENABLED:-true}
    volumes:
      # Remember, n8n still needs local storage for encryption keys!
      - n8n_storage:/home/node/.n8n

volumes:
  postgres_data:
    external: true
    # Replace 'repo-a-folder-name_postgres_data' with the actual volume name from 'docker volume ls'
    name: odin-recruitment_postgres_data
  n8n_storage:
    external: true
    name: odin-recruitment_n8n_storage
